# n8n with PostgreSQL and ngrok for public access
# n8n documentation: https://docs.n8n.io/hosting/installation/docker/

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_this_password}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"  # Port for local development and ngrok
    environment:
      # Database connection
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-change_this_password}

      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-change_this_password}
      - N8N_RUNNERS_ENABLED=true

      # Host configuration
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - WEBHOOK_URL=${NGROK_PUBLIC_URL:-http://localhost:5678}

      # Execution settings
      - GENERIC_TIMEZONE=Asia/Taipei
      - TZ=Asia/Taipei

    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

  ngrok:
    image: ngrok/ngrok:3-alpine
    restart: unless-stopped
    ports:
      - 4040:4040
    command:
      - "http"
      - "http://host.docker.internal:5678"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - n8n_network

networks:
  n8n_network:
    name: n8n_network
    driver: bridge

volumes:
  n8n_postgres_data:
    name: n8n_public_postgres_data  # Stores PostgreSQL database files
  n8n_data:
    name: n8n_public_data  # Stores n8n workflows, credentials, and binary data
